name: flixboy_app
description: "Flixboy - Tu plataforma de streaming."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ── ORIGINALES ─────────────────────────────────────────────
  cupertino_icons: ^1.0.6
  video_player: ^2.9.2
  http: ^1.2.2

  # ── FIREBASE ───────────────────────────────────────────────
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # ── ALMACENAMIENTO LOCAL ────────────────────────────────────
  # SharedPreferences: solo para perfiles y watchlist (NO tokens)
  shared_preferences: ^2.2.2

  # ── SEGURIDAD ──────────────────────────────────────────────
  # Almacenamiento cifrado AES-256 (KeyStore/Keychain) — para tokens
  flutter_secure_storage: ^9.2.2
  # Hash SHA-256 para PINs
  crypto: ^3.0.3
  cached_network_image: ^3.3.1
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^17.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/profile1.jpg
    - assets/images/profile2.jpg
    - assets/images/profile3.jpg
    - assets/images/profile4.jpg
    - assets/images/profile5.jpg